### ISSUE TITLE
Fatal error on Safari

### ISSUE THREAD

**Issue by wpsoul** [bradicalone/convert-svg-react#15]
This package generates fatal error on safari and destroyed all scripts.

Reason is that in format.js, you used lookbehind regex which is not supported by Safari, IOS, IE

[https://caniuse.com/js-regexp-lookbehind](url)

Also, many simple svg also will break script because of error RangeError: Invalid count value at String.repeat (also in format.js)

Example of SVG

`<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="70px" height="70" viewBox="0 0 503.097 503.097" style="fill:#fff;" xml:space="preserve">
<g>
	<g>
		<path d="M412.438,189.759c-1.214-0.048-2.28,0.125-3.275,0.396c-45.108-4.562-90.795-6.305-136.547-6.355
			c13.543-17.98,35.576-20.367,57.574-28.038c25.11-8.751,35.683-28.822,32.834-54.821c-1.803-16.479-27.822-16.656-26,0
			c3.129,28.541-15.437,30.419-38.566,36.975c-24.166,6.848-44.346,19.847-54.556,43.564c-0.368,0.853-0.612,1.696-0.805,2.534
			c-49.681,0.68-99.317,3.062-148.279,5.745c-0.526,0.031-0.998,0.14-1.483,0.229c-0.831-0.167-1.708-0.269-2.681-0.229
			c-79.313,3.209-108.552,96.959-79.892,164.004c13.192,30.869,41.642,55.7,75.423,59.991
			c51.303,6.515,92.018-26.278,114.798-69.477c33.814,2.076,67.646,0.959,101.501,0.716c22.846,42.848,63.403,75.245,114.427,68.761
			c33.784-4.291,62.231-29.122,75.424-59.991C520.994,286.718,491.76,192.968,412.438,189.759z M472.986,346.201
			c-11.501,23.191-32.103,44.849-59.438,47.145c-44.488,3.737-76.286-25.07-95.227-63.028c-0.914-1.833-2.123-3.087-3.464-3.94
			c-1.625-1.381-3.778-2.27-6.525-2.265c-37.871,0.132-75.71,1.741-113.523-1.041c-5.284-0.392-8.439,2.625-9.546,6.464
			c-0.16,0.265-0.343,0.488-0.487,0.782c-18.944,37.958-50.742,66.766-95.232,63.028c-27.33-2.291-47.931-23.948-59.433-47.145
			c-25.989-52.399-2.019-133.078,60.547-135.612c0.513-0.021,0.973-0.124,1.445-0.203c0.843,0.163,1.731,0.257,2.719,0.203
			c109.042-5.979,221.443-10.583,330.157,2.084c1.031,0.12,1.95,0.069,2.818-0.061C478.761,224.149,496.721,298.342,472.986,346.201
			z"></path>
		<path d="M130.396,277.812h-18.492V264.71c0-20.5-31.938-20.505-31.938,0v13.102H64.705c-4.71,0-8.887,1.843-11.756,5.174
			c-2.491,2.899-3.859,6.739-3.859,10.796c0,7.938,5.36,15.971,15.615,15.971h15.262v16.336c0,10.252,8.033,15.614,15.968,15.614
			c7.937,0,15.97-5.362,15.97-15.614v-16.336h18.492c10.252,0,15.615-8.033,15.615-15.971
			C146.011,285.845,140.648,277.812,130.396,277.812z"></path>
		<path d="M408.212,243.354c-4.712,0-8.886,1.841-11.755,5.172c-2.494,2.897-3.859,6.729-3.859,10.796
			c0,7.937,5.357,15.971,15.614,15.971c4.713,0,8.887-1.844,11.756-5.175c2.493-2.899,3.859-6.729,3.859-10.796
			C423.827,251.388,418.465,243.354,408.212,243.354z"></path>
		<path d="M370.523,288.582c-4.713,0-8.887,1.843-11.75,5.174c-2.494,2.895-3.865,6.729-3.865,10.791
			c0,7.937,5.363,15.97,15.615,15.97c4.712,0,8.887-1.843,11.75-5.179c2.494-2.895,3.865-6.724,3.865-10.791
			C386.144,296.615,380.775,288.582,370.523,288.582z"></path>
		<path d="M440.519,284.275c-4.713,0-8.887,1.844-11.751,5.175c-2.493,2.895-3.864,6.728-3.864,10.79
			c0,7.938,5.362,15.971,15.615,15.971c4.712,0,8.886-1.844,11.75-5.18c2.493-2.895,3.864-6.723,3.864-10.791
			C456.133,292.309,450.771,284.275,440.519,284.275z"></path>
		<path d="M407.136,319.812c-4.713,0-8.887,1.843-11.751,5.174c-2.493,2.895-3.864,6.729-3.864,10.791
			c0,7.937,5.357,15.97,15.615,15.97c4.712,0,8.887-1.843,11.75-5.179c2.493-2.895,3.864-6.724,3.864-10.791
			C422.75,327.845,417.388,319.812,407.136,319.812z"></path>
		<path d="M232.697,259.51h-24.768c-10.248,0-15.615,8.034-15.615,15.966c0,7.937,5.362,15.97,15.615,15.97h24.768
			c10.248,0,15.615-8.033,15.615-15.97C248.312,267.544,242.944,259.51,232.697,259.51z"></path>
		<path d="M305.916,259.51h-26.923c-10.253,0-15.615,8.034-15.615,15.966c0,7.937,5.362,15.97,15.615,15.97h26.923
			c10.253,0,15.615-8.033,15.615-15.97C321.531,267.544,316.169,259.51,305.916,259.51z"></path>
	</g>
</g>
</svg>`

**Comment by bradicalone** [comment]
Yeah Safari doesn't support look behinds, thought I got them all. Will update, Thanks!

**Comment by bradicalone** [comment]
Updated and also refactored a bunch now a stable version 1.0.0
