### ISSUE TITLE
undefined childNodes on ReactJS

### ISSUE THREAD

**Issue by Ali-Ozturk** [bradicalone/convert-svg-react#3]
When trying to use identical code from your examples of the Client (ReactJS) I'm receiving the following error;

> Cannot read property 'childNodes' of undefined

A codebox example can be found on;
https://codesandbox.io/s/focused-napier-493tt?file=/src/App.js 

I want to use your library for a project of mine and would love for this to work on ReactJS

**Comment by bradicalone** [comment]
Issue taken care of. Updated NPM. go ahead and `npm i convert-svg-react@1.0.0-beta.7` 
Have some styling to take care later on, but it's working and updating your svg string.
